backend:
  name: github
  repo: PatrykJelonek/blog
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "tags"
    label: "Tagi"
    folder: "content/tags"
    create: true
    slug: "{{id}}"
    fields:
      - {label: "Nazwa", name: "name", widget: "string"}
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Opis", name: "description", widget: "string"}
  - name: "posts"
    label: "Posty"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Tagi"
        name: "tags"
        widget: "relation"
        collection: "tags"
        multiple: true
        search_fields: ["name"]
        value_field: "id"
        display_fields: ["name"]
      
